modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/TeamFelnull/OtyacraftEngine/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "otyacraftengine"
version = "${version}"
displayName = "Otyacraft Engine"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/otyacraft-engine"
updateJSONURL = "https://raw.githubusercontent.com/TeamFelnull/OtyacraftEngine/master/version_check.json"
authors = "MORIMORI0317"
credits = "FelNull developers"
description = '''
This mod is an integrated library used by FelNull developers.
The ikisugi dependency mod...
'''
logoFile = "logo.png"

[modproperties.otyacraftengine]
catalogueImageIcon = "icon.png"

[[dependencies.otyacraftengine]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.otyacraftengine]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.otyacraftengine]]
modId = "architectury"
mandatory = true
versionRange = "[5.6.22,)"
ordering = "AFTER"
side = "BOTH"