modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/TeamFelnull/OtyacraftEngine/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "otyacraftengine"
version = "${version}"
displayName = "Otyacraft Engine"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/otyacraft-engine"
updateJSONURL = "https://raw.githubusercontent.com/TeamFelnull/OtyacraftEngine/master/version_check.json"
authors = "MORIMORI0317"
credits = "FelNull developers"
description = '''
Integrated library used by felnull developers.
The ikisugi dependency mod...
'''
logoFile = "logo.png"

[modproperties.otyacraftengine]
catalogueImageIcon = "icon.png"

[[dependencies.otyacraftengine]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.otyacraftengine]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.otyacraftengine]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.otyacraftengine]]
modId = "cloth_config"
mandatory = true
versionRange = "[8.0.75,)"
ordering = "NONE"
side = "BOTH"