modLoader = "javafml"
loaderVersion = "47.4.0"
issueTrackerURL = "https://github.com/Mod-Sauce/OtyacraftEngineRenewed/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "otyacraftengine"
version = "${version}"
displayName = "Otyacraft Engine"
displayURL = "mod-sauce.github.io/oer.html"
updateJSONURL = ""
authors = "Shadowbe27, Mooo0042"
credits = "Mod Sauce & contributers"
description = '''
Integrated library used by felnull developers.
The ikisugi dependency mod...
'''
logoFile = "logo.png"

[modproperties.otyacraftengine]
catalogueImageIcon = "icon.png"

[[dependencies.otyacraftengine]]
modId = "forge"
mandatory = true
versionRange = "47.4.0"
ordering = "NONE"
side = "BOTH"

[[dependencies.otyacraftengine]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.1
ordering = "NONE"
side = "BOTH"

[[dependencies.otyacraftengine]]
modId = "architectury"
mandatory = true
versionRange = "9.2.14"
ordering = "AFTER"
side = "BOTH"

[[dependencies.otyacraftengine]]
modId = "cloth_config"
mandatory = true
versionRange = "11.1.136"
ordering = "NONE"
side = "BOTH"