name: Mod Build
on:
  - workflow_dispatch

jobs:
  build:
    runs-on: codeberg-medium
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build --no-daemon
      - name: Upload Fabric
        uses: actions/upload-artifact@v3.2.2
        with:
          path: |
            fabric/build/libs
            neoforge/build/libs
          retention-days: 30
          archive: true
