modLoader="javafml"
loaderVersion="[32,)" 
issueTrackerURL="https://github.com/TeamFelnull/OtyacraftEngine/issues"
logoFile="logo.png" 
[[mods]]
modId="otyacraftengine"
version="${file.jarVersion}" 
displayName="Otyacraft Engine"
updateJSONURL="https://raw.githubusercontent.com/TeamFelnull/OtyacraftEngine/master/update_check.json" 
displayURL="https://github.com/TeamFelnull/OtyacraftEngine" 
credits="TeamFelNull"
authors="MORIMORI0317" 
description="Thank you for downloading!\nThis mod is my mod integration library."
