architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/otyacraftenginerenewed.accesswidener")
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "dev.architectury:architectury:${rootProject.architectury_version}"
    modApi "me.shedaniel.cloth:cloth-config:${rootProject.cloth_config_version}"
    implementation "dev.felnull:felnull-java-library:${rootProject.felnull_version}"
    implementation 'com.madgag:animated-gif-lib:1.4'
}

publishing {
repositories {
    maven {
      name = "CodebergPakages"
      url = "https://codeberg.org/api/packages/Mod-Sauce/maven"

      credentials(HttpHeaderCredentials) {
        name = "Authorization"
        value = "token " + (System.getenv("OER_TOKEN_SHADOWBEE") ?: "")
      }

      authentication {
        header(HttpHeaderAuthentication)
      }
    }
  }

    publications {
        maven(MavenPublication) {
            from(components.java)
            groupId = "org.mod-sauce" // or whatever you want
            artifactId = "otyacraftenginerenewed" // fabric, forge, or nothing
            version = rootProject.version
        }
    }
}
