modLoader = "javafml"
loaderVersion = "[43,)"
license = "IKISUIG LICENSE"

[[mods]]
modId = "otyacraftenginetest"
version = "114514"
displayName = "Otyacraft Engine Test"
authors = "MORIMORI0317"
description = '''
The otyacraft engine test mod.
'''
#logoFile = ""