plugins {
    id("com.gradleup.shadow") version "9.4.1"
    id 'com.matthewprenger.cursegradle' version '1.4.0'
    id "com.modrinth.minotaur" version "2.8.0"
    id 'net.neoforged.moddev' version '2.0.115'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}


//neoForge {
//    convertAccessWideners = true
//    extraAccessWideners.add loom.accessWidenerPath.get().asFile.name
//
//    mixinConfig "otyacraftenginerenewed-common.mixins.json"
//    mixinConfig "otyacraftenginerenewed.mixins.json"
//}

neoForge {
    accessTransformers {
        file("src/main/resources/META-INF/accesstransformer.cfg")
    }
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
    neoforgeDependencies.extendsFrom shadowIn
    shadowCommon.extendsFrom shadowIn
}

dependencies {
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"

    modApi "dev.architectury:architectury-neoforge:${rootProject.architectury_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive = false }

    modApi "me.shedaniel.cloth:cloth-config-neoforge:${rootProject.cloth_config_version}"
    modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${rootProject.rei_version}"

    implementation "dev.felnull:felnull-java-library:${rootProject.felnull_version}"
    implementation 'com.madgag:animated-gif-lib:1.4'
    developmentNeoForge "dev.felnull:felnull-java-library:${rootProject.felnull_version}"
    developmentNeoForge 'com.madgag:animated-gif-lib:1.4'
    shadowIn "dev.felnull:felnull-java-library:${rootProject.felnull_version}"
    shadowIn 'com.madgag:animated-gif-lib:1.4'
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowIn]
    relocate('dev.felnull.fnjl', 'org.modsauce.otyacraftenginerenewed.include.dev.felnull.fnjl')
    relocate 'com.madgag', 'org.modsauce.otyacraftenginerenewed.include.com.madgag'
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier.set("dev-shadow")
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set(null)
    archiveFileName.set("OtyacraftEngineRenewed-Fabric-${project.version}.jar")
}

jar {
    archiveClassifier.set("org")
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

// def javaComponent = components["java"] as AdhocComponentWithVariants
// javaComponent.withVariantsFromConfiguration(configurations["shadowRuntimeElements"]) {
//     // See more details in https://github.com/GradleUp/shadow/pull/1662.
//     skip()
// }

publishing {
repositories {
repositories {
    maven {
        name = "CodebergPackages"
        url = "https://codeberg.org/api/packages/Mod-Sauce/maven"

        credentials {
            username = System.getenv("CODEBERG_USERNAME") ?: "shadowbee"
            password = System.getenv("PKGTOKEN") ?: ""
        }
    }
}


    publications {
        maven(MavenPublication) {
            from(components.java)
            groupId = "org.mod-sauce" // or whatever you want
            artifactId = "otyacraftenginerenewed-neoforge" // fabric, forge, or nothing
            version = rootProject.version
        }
    }
}
