name: Publish
on:
  release:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3.5.0
      - name: Publish package
        uses: gradle/gradle-build-action@v3.5.0
        with:
          arguments: publish
        env:
          USERNAME: ${{ secrets.USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.PASSWORD }}
