name: Publish
on:
  release:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v3
      - uses: useblacksmith/setup-java@v5
        with:
          java-version: "17"
          distribution: "zulu"
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3.5.0
      - run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew publish
        env:
          OER_TOKEN_SHADOWBEE: ${{ secrets.OER_TOKEN_SHADOWBEE }}
